version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: innovacion-contable-frontend
    ports:
      - "3030:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx
